"""HTML report generation."""

from __future__ import annotations

from pathlib import Path
from typing import Any

_VERDICT_COLORS = {
    "COMPLIANT": "#2d6a4f",
    "VIOLATION": "#d00000",
    "INCONCLUSIVE": "#e85d04",
}


def generate_html_report(report_data: dict[str, Any], output_path: Path | str) -> Path:
    """Generate an HTML report from JSON report data."""
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    verdict = report_data.get("final_verdict", "N/A")
    color = _VERDICT_COLORS.get(verdict, "#555")
    summary = report_data.get("summary", {})
    coverage = report_data.get("coverage", {})
    findings = report_data.get("findings", [])

    findings_html = ""
    for f in findings:
        fc = _VERDICT_COLORS.get(f.get("verdict", ""), "#555")
        findings_html += (
            f'<tr>'
            f'<td><code>{f.get("evidence_id", "")[:8]}</code></td>'
            f'<td style="color:{fc};font-weight:bold">{f.get("verdict", "")}</td>'
            f'<td>{f.get("capability", "")}</td>'
            f'<td>{f.get("reason", "")}</td>'
            f'</tr>\n'
        )
    if not findings_html:
        findings_html = (
            '<tr><td colspan="4" style="text-align:center;color:#888">'
            "No findings</td></tr>"
        )

    coverage_pct = f'{coverage.get("coverage_ratio", 0):.0%}'

    html = f"""\
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>BioDrift Report — {report_data.get("package_id", "")}</title>
<style>
  body {{ font-family: system-ui, sans-serif;
         max-width: 800px; margin: 2rem auto;
         padding: 0 1rem; color: #222; }}
  h1 {{ border-bottom: 2px solid #ddd; padding-bottom: .5rem; }}
  .verdict {{ font-size: 1.8rem; font-weight: bold; color: {color}; margin: 1rem 0; }}
  table {{ width: 100%; border-collapse: collapse; margin: 1rem 0; }}
  th, td {{ text-align: left; padding: .5rem; border-bottom: 1px solid #eee; }}
  th {{ background: #f5f5f5; }}
  code {{ background: #f0f0f0; padding: .15rem .4rem; border-radius: 3px; font-size: .9rem; }}
  .meta {{ color: #666; font-size: .9rem; }}
</style>
</head>
<body>
<h1>BioDrift Verification Report</h1>
<p class="meta">Package: <strong>{report_data.get("package_id", "")}</strong>
 &middot; Run: <code>{report_data.get("run_id", "")[:12]}</code>
 &middot; {report_data.get("timestamp", "")}</p>
<p class="meta">Version: {report_data.get("candidate_version", "")}
 &middot; Digest: <code>{report_data.get("package_digest", "")[:12]}</code></p>

<div class="verdict">{verdict}</div>

<table>
<tr><th>Events</th><th>Coverage</th><th>Findings</th></tr>
<tr>
  <td>{summary.get("total_events", 0)}</td>
  <td>{coverage_pct}</td>
  <td>{summary.get("total_findings", 0)}</td>
</tr>
</table>

<h2>Findings</h2>
<table>
<tr><th>ID</th><th>Verdict</th><th>Capability</th><th>Reason</th></tr>
{findings_html}</table>

<hr>
<p class="meta">Generated by BioDrift v0.1.0</p>
</body>
</html>"""

    with open(path, "w") as f:
        f.write(html)
    return path
